//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VckWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingcode
    {
        public int ID { get; set; }
        public string accesstoken { get; set; }
        public string card_id { get; set; }
        public string bookingcode1 { get; set; }
        public Nullable<int> valueincent { get; set; }
        public Nullable<System.DateTime> valid_until { get; set; }
    }
}
