//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VckWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clearing_log
    {
        public int ID { get; set; }
        public string unit_id { get; set; }
        public Nullable<int> C_1_EUROCENT_HOPPER { get; set; }
        public Nullable<int> C_2_EUROCENT_HOPPER { get; set; }
        public Nullable<int> C_5_EUROCENT_HOPPER { get; set; }
        public Nullable<int> C_10_EUROCENT_HOPPER { get; set; }
        public Nullable<int> C_20_EUROCENT_HOPPER { get; set; }
        public Nullable<int> C_50_EUROCENT_HOPPER { get; set; }
        public Nullable<int> C_100_EUROCENT_HOPPER { get; set; }
        public Nullable<int> C_200_EUROCENT_HOPPER { get; set; }
        public Nullable<int> all_hopper_value { get; set; }
        public Nullable<int> BILL_TYPE_01 { get; set; }
        public Nullable<int> BILL_TYPE_02 { get; set; }
        public Nullable<int> BILL_TYPE_03 { get; set; }
        public Nullable<int> BILL_TYPE_04 { get; set; }
        public Nullable<int> BILL_TYPE_05 { get; set; }
        public Nullable<int> BILL_TYPE_06 { get; set; }
        public Nullable<int> BILL_TYPE_07 { get; set; }
        public Nullable<int> BILL_TYPE_08 { get; set; }
        public Nullable<int> bills_value { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
