//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VckWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hw_dispenser_accounts
    {
        public int ID { get; set; }
        public string unit_id { get; set; }
        public string account_id { get; set; }
        public Nullable<int> number_of_cards { get; set; }
    }
}
