//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VckWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hw_failed_payouts
    {
        public int ID { get; set; }
        public string card_id { get; set; }
        public Nullable<int> payout_needed { get; set; }
        public Nullable<int> payout_done { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public bool done { get; set; }
    }
}
