//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VckWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vouchercard_clearing_log
    {
        public int ID { get; set; }
        public string unit_id { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public decimal number { get; set; }
        public int amount_cash { get; set; }
        public int amount_cashless { get; set; }
        public int tray1_dispensed_amount { get; set; }
        public int tray2_dispensed_amount { get; set; }
        public int tray3_dispensed_amount { get; set; }
        public int tray4_dispensed_amount { get; set; }
        public int tray5_dispensed_amount { get; set; }
        public int tray6_dispensed_amount { get; set; }
        public int tray7_dispensed_amount { get; set; }
        public int tray8_dispensed_amount { get; set; }
        public int tray1_current_amount { get; set; }
        public int tray2_current_amount { get; set; }
        public int tray3_current_amount { get; set; }
        public int tray4_current_amount { get; set; }
        public int tray5_current_amount { get; set; }
        public int tray6_current_amount { get; set; }
        public int tray7_current_amount { get; set; }
        public int tray8_current_amount { get; set; }
    }
}
