//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VckWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet_cards
    {
        public int ID { get; set; }
        public string UID { get; set; }
        public Nullable<int> Issuer { get; set; }
        public Nullable<byte> VersHi { get; set; }
        public Nullable<byte> VersLo { get; set; }
        public Nullable<byte> PartnerID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<byte> CardType { get; set; }
        public Nullable<byte> CardMotive { get; set; }
        public Nullable<byte> CardLevel { get; set; }
        public Nullable<int> Ext_trans_counter { get; set; }
        public Nullable<int> Trans_Counter { get; set; }
        public Nullable<int> Valid_From { get; set; }
        public Nullable<int> Valid_To { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> Deposit_Currency { get; set; }
        public Nullable<byte> LifecycleCounter { get; set; }
        public Nullable<byte> CardStatus { get; set; }
        public Nullable<int> Balance1 { get; set; }
        public Nullable<int> PrevBalance1 { get; set; }
        public Nullable<int> MaxBalance { get; set; }
        public Nullable<int> LastChange { get; set; }
        public Nullable<int> Bal1CurrencyCode { get; set; }
        public Nullable<byte> Balance1_Status { get; set; }
        public string IMEI { get; set; }
        public string ICCID { get; set; }
    }
}
