//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlanningApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public int RoundId { get; set; }
        public string Catogory { get; set; }
        public Nullable<int> Pair1 { get; set; }
        public Nullable<int> Pair2 { get; set; }
        public Nullable<int> Pair3 { get; set; }
        public Nullable<int> Pair4 { get; set; }
        public Nullable<int> Pair5 { get; set; }
    
        public virtual TeamPair TeamPair { get; set; }
        public virtual TeamPair TeamPair1 { get; set; }
        public virtual TeamPair TeamPair2 { get; set; }
        public virtual TeamPair TeamPair3 { get; set; }
        public virtual TeamPair TeamPair4 { get; set; }
    }
}
