//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePlanningApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamsDBEntities1 : DbContext
    {
        public TeamsDBEntities1()
            : base("name=TeamsDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<TeamPair> TeamPairs { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
